var express = require('express');
var router = express.Router();

// Include Parse
var Parse = require('parse/node');
Parse.initialize(process.env.PARSE_APP_ID, process.env.PARSE_JS_KEY);
Parse.User.enableUnsafeCurrentUser();

/* GET the logout page goes back to home */
router.get('/', function(req, res, next) {
  res.redirect('/');
});

/* POST logs the user out */
router.post('/', function(req, res, next) {
  
  // Get the presence cookie that we made to determine if they are logged in
  var loggedIn = req.cookies['presence'];
  
  // If the user has not logged in yet, tell them
  if (!loggedIn) {
    res.render('login', {
      error: 'No user logged in',
      message: 'you have cookie: ' + req.cookies['presence']
    });
    return;
  }
  
  // Sets the Parse.User to the user that made the request.
  // The cookie 'presence' is the session token generated by
  // Parse.signUp() or Parse.logIn()
  Parse.User.become(loggedIn).then(function (user) {
    // The current user is now set to user.

    // Logs out the current user
    Parse.User.logOut();

    // Removes the cookie and sends them to the login page
    res.clearCookie('presence');
    res.render('index', {
      message: 'you have cookie: ' + req.cookies['presence'] + ' '
                + user.getUsername() + ' has been logged out'
    });
    
  }, function (error) {
    // The token could not be validated.
    res.render('login', {
      error: "Unable to logout. Couldn't become user. " + error.message,
      message: 'you have cookie: ' + req.cookies['presence']
    });
  });
});

module.exports = router;